# Generated by Django 2.2 on 2020-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190929_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_view',
            field=models.IntegerField(default=0),
        ),
    ]
